declare module 'basicscroll';
declare module 'react-lottie';
declare module 'react-pay-icons';
declare module 'react-scrollspy-navigation';
declare module 'reflexbox';
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.svg'
